 name: S87Powers
 version: .03
 depend: [PermissionsEx, Vault]
 description: This plugin provides a variety of awesome powers for users to wield
 author: RamanujansGhost
 authors: [knightfallx66] 
 website: "https://github.com/RamanujansGhost/s87powers/wiki"
 
 main: io.github.ramanujansghost.s87powers.S87Powers
 
 commands: 
     powers:
     
 #Add commands and further documentation