 name: S87Powers
 version: .06
 depend: [PermissionsEx, Vault]
 softdepend: [Factions]
 description: This plugin provides a variety of awesome powers for users to wield
 author: RamanujansGhost
 authors: [RamanujansGhost, knightfallx66] 
 website: "https://github.com/RamanujansGhost/s87powers/wiki"
 
 main: io.github.ramanujansghost.s87powers.S87Powers
 
 commands: 
     powers:
 
 permissions:
  s87powers.add:
    description: Allows player to give new power permissions
    default: op
       
  s87powers.remove:
    description: Allows player to remove current powers permissions
    default: op
       
  s87powers.lookup:
    description: Allows player to look up a players' current powers permissions
    default: op 

  s87powers.bestialtransmutation:
    description: Allows player to spawn animals using life, meat, and redstone
    default: false
    
  s87powers.bestialtransmutation.toggledon:
    description: Allows player to toggle bestialtransmutation
    default: false
       
  s87powers.lumberjack:
    description: Allows player to rapidly cut down trees
    default: false
    
  s87powers.lumberjack.toggledon:
    description: Allows player to toggle lumberjack
    default: false

  s87powers.wolfpack:
    description: Allows player to spawn up to 3 wolves every 5 minutes
    default: false
 
  s87powers.wolfpack.toggledon:
    description: Allows player to toggle wolfpack
    default: false
       
  s87powers.reflexes:
    description: Allows player to catch incoming arrows
    default: false
    
  s87powers.reflexes.toggledon:
    description: Allows player to toggle reflexes
    default: false

  s87powers.chargebow:
    description: This power allows the player to shoot powerful fireballs from their bow at a cost of 1 fire charge per shot
    default: false

  s87powers.chargebow.toggledon:
    description: Allows player to toggle chargebow
    default: false
 #Add commands and further documentation